# Generated by Django 4.1.4 on 2023-01-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='desired_gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Женщины | Females'), (2, 'Мужчины | Males'), (3, 'Смешанно | Mixed'), (4, "Не важно | Doesn't matter")]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='gender_of_living',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Женщины | Females'), (2, 'Мужчины | Males'), (3, 'Смешанно | Mixed'), (4, "Не важно | Doesn't matter")]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number_of_rooms',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4+')]),
        ),
    ]
